name       : libvirt-glib
version    : 4.0.0
release    : 24
source     :
    - https://libvirt.org/sources/glib/libvirt-glib-4.0.0.tar.xz : 8423f7069daa476307321d1c11e2ecc285340cd32ca9fc05207762843edeacbd
license    : LGPL-2.1-or-later
component  : virt
summary    : libvirt is a C toolkit to interact with the virtualization capabilities of recent versions of Linux
description: |
    libvirt is a C toolkit to interact with the virtualization capabilities of recent versions of Linux (and other OSes). It is free software available under the GNU Lesser General Public License. Virtualization on the Linux Operating System means the ability to run multiple instances of Operating Systems concurrently on a single hardware system where the basic resources are driven by a Linux instance. The library aim at providing long term stable C API initially for the Xen paravirtualization but should be able to integrate other virtualization mechanisms if needed.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libvirt)
    - intltool
    - valadoc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
