name       : libvirt-glib
version    : 1.0.0
release    : 9
source     :
    - https://libvirt.org/sources/glib/libvirt-glib-1.0.0.tar.gz : ca9158d01cc4d9e0218f94f8c9ee04ae367d8c3b4396daaebca2c4b89a2e8a47
license    : GPL-2.0-only
component  : virt
summary    : libvirt is a C toolkit to interact with the virtualization capabilities of recent versions of Linux
description: |
    libvirt is a C toolkit to interact with the virtualization capabilities of recent versions of Linux (and other OSes). It is free software available under the GNU Lesser General Public License. Virtualization on the Linux Operating System means the ability to run multiple instances of Operating Systems concurrently on a single hardware system where the basic resources are driven by a Linux instance. The library aim at providing long term stable C API initially for the Xen paravirtualization but should be able to integrate other virtualization mechanisms if needed.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(libvirt)
    - intltool
    - valadoc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
